In [2]:
import numpy as np
np.array([[1,2,3],[4,5,6]]).tolist()


[[1, 2, 3], [4, 5, 6]]

In [9]:
import numpy as np
the_array = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(the_array)
trace = np.trace(the_array)
  
print(trace)


[[10 20 30]
 [40 50 60]
 [70 80 90]]
150
